### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by BryanJY-Wong** [ACloudGuru/metadata-env-buildkite-plugin#5]
Hi, I've noticed that currently the plugin _requires_ metadata to exist to inject them into env vars and I realized that this may limit the use case to converting values supplied by block-steps into env vars or cases where the user knows that the metadata will exist.

I was wondering if you're interested in extending this plugin to allow default values to be defined. So if a metadata doesn't exist it will assign a default value to the env vars.

Also, the current implementation actually overrides the env vars with the metadata values even if the env vars are defined previously. I'd also like to prevent this from happening.

I have actually forked this repo and implemented these features, if you're willing to review the code I can raise a PR and make any necessary changes to the implementation that's needed.

**Comment by shays10** [comment]
Hi, this is super useful! Any chance this can get merged upstream? :)
